FROM alpine:3
ADD https://mailfud.org/geoip-legacy/GeoIP.dat.gz /tmp/
ADD https://mailfud.org/geoip-legacy/GeoIPv6.dat.gz /tmp/
RUN gzip -d /tmp/*.gz

FROM optix2000/deluge-base
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing py3-geoip
COPY --from=0 /tmp/GeoIP.dat /usr/share/GeoIP/
COPY --from=0 /tmp/GeoIPv6.dat /usr/share/GeoIP/
